### ISSUE TITLE
Problem Running EuRoC Dataset

### ISSUE THREAD

**Issue by arjunskumar** [alejandrofontan/AnyFeature-VSLAM#1]
# Problem Running EuRoC Dataset

## Environment
- Dataset: EuRoC
- Sequence: MH_01

## Steps Taken

1. Created a `euroc_sequence` folder with the following structure and copied `MH_01/mav0/cam0/data` to `euroc_sequence/rgb` :
   ```
   euroc_sequence/
   └── rgb/
       └── [image files] 
   ```

2. Generated a `rgb.txt` file with the following content:
   ```
   1403636741763555584 rgb/1403636741763555584.png
   1403636620813555456 rgb/1403636620813555456.png
   1403636597963555584 rgb/1403636597963555584.png
   ```

3. Modified `calibration.yaml` as follows:
   ```yaml
   %YAML:1.0
   # Camera calibration and distortion parameters (OpenCV)
   Camera.fx: 458.654
   Camera.fy: 457.296
   Camera.cx: 367.215
   Camera.cy: 248.375
   Camera.k1: -0.28340811
   Camera.k2: 0.07395907
   Camera.p1: 0.00019359
   Camera.p2: 1.76187114e-05
   Camera.k3: 0.0
   Camera.w: 752
   Camera.h: 480
   # Camera frames per second
   Camera.fps: 20.0
   #Camera.RGB: false
   ```

## Command Run
```
./bin/mono "sequence_path:docs/euro_sequence"
```

## Output
![image](https://github.com/user-attachments/assets/b41bfb08-7d67-4d83-9037-de5efdc9cd1b)

## Questions
1. Are there any issues with my steps?
